package labonnealternance

// nolint: misspell
var romes = map[string][]string{
	"A1101": {"Engins", "Agricole", "Forestier"},
	"A1201": {"Espaces", "Naturel", "Vert"},
	"A1202": {"Espaces", "Naturel", "Vert"},
	"A1203": {"Espaces", "Naturel", "Vert"},
	"A1204": {"Espaces", "Naturel", "Vert"},
	"A1205": {"Espaces", "Naturel", "Vert"},
	"A1301": {"Étude", "Assistance", "Technique"},
	"A1302": {"Étude", "Assistance", "Technique"},
	"A1303": {"Étude", "Assistance", "Technique"},
	"A1401": {"Production"},
	"A1402": {"Production"},
	"A1403": {"Production"},
	"A1404": {"Production"},
	"A1405": {"Production"},
	"A1406": {"Production"},
	"A1407": {"Production"},
	"A1408": {"Production"},
	"A1409": {"Production"},
	"A1410": {"Production"},
	"A1411": {"Production"},
	"A1412": {"Production"},
	"A1413": {"Production"},
	"A1414": {"Production"},
	"A1415": {"Production"},
	"A1416": {"Production"},
	"A1417": {"Production"},
	"A1501": {"Soin", "Animaux"},
	"A1502": {"Soin", "Animaux"},
	"A1503": {"Soin", "Animaux"},
	"A1504": {"Soin", "Animaux"},
	"B1101": {"Art", "Plastique"},
	"B1201": {"Céramique"},
	"B1301": {"Décoration"},
	"B1302": {"Décoration"},
	"B1303": {"Décoration"},
	"B1401": {"Fibre", "Papier"},
	"B1402": {"Fibre", "Papier"},
	"B1501": {"Instrument", "Musique"},
	"B1601": {"Métal", "Verre", "Bijouterie", "Horlogerie"},
	"B1602": {"Métal", "Verre", "Bijouterie", "Horlogerie"},
	"B1603": {"Métal", "Verre", "Bijouterie", "Horlogerie"},
	"B1604": {"Métal", "Verre", "Bijouterie", "Horlogerie"},
	"B1701": {"Taxidermie"},
	"B1801": {"Tissu", "Cuir"},
	"B1802": {"Tissu", "Cuir"},
	"B1803": {"Tissu", "Cuir"},
	"B1804": {"Tissu", "Cuir"},
	"B1805": {"Tissu", "Cuir"},
	"B1806": {"Tissu", "Cuir"},
	"C1101": {"Assurance"},
	"C1102": {"Assurance"},
	"C1103": {"Assurance"},
	"C1104": {"Assurance"},
	"C1105": {"Assurance"},
	"C1106": {"Assurance"},
	"C1107": {"Assurance"},
	"C1108": {"Assurance"},
	"C1109": {"Assurance"},
	"C1110": {"Assurance"},
	"C1201": {"Banque"},
	"C1202": {"Banque"},
	"C1203": {"Banque"},
	"C1204": {"Banque"},
	"C1205": {"Banque"},
	"C1206": {"Banque"},
	"C1207": {"Banque"},
	"C1301": {"Finance"},
	"C1302": {"Finance"},
	"C1303": {"Finance"},
	"C1401": {"Gestion", "Administrative", "Banque", "Assurance"},
	"C1501": {"Immobilier"},
	"C1502": {"Immobilier"},
	"C1503": {"Immobilier"},
	"C1504": {"Immobilier"},
	"D1101": {"Commerce", "Alimentaire", "Bouche"},
	"D1102": {"Commerce", "Alimentaire", "Bouche"},
	"D1103": {"Commerce", "Alimentaire", "Bouche"},
	"D1104": {"Commerce", "Alimentaire", "Bouche"},
	"D1105": {"Commerce", "Alimentaire", "Bouche"},
	"D1106": {"Commerce", "Alimentaire", "Bouche"},
	"D1107": {"Commerce", "Alimentaire", "Bouche"},
	"D1201": {"Commerce", "Alimentaire", "Prestation", "Confort"},
	"D1202": {"Commerce", "Alimentaire", "Prestation", "Confort"},
	"D1203": {"Commerce", "Alimentaire", "Prestation", "Confort"},
	"D1204": {"Commerce", "Alimentaire", "Prestation", "Confort"},
	"D1205": {"Commerce", "Alimentaire", "Prestation", "Confort"},
	"D1206": {"Commerce", "Alimentaire", "Prestation", "Confort"},
	"D1207": {"Commerce", "Alimentaire", "Prestation", "Confort"},
	"D1208": {"Commerce", "Alimentaire", "Prestation", "Confort"},
	"D1209": {"Commerce", "Alimentaire", "Prestation", "Confort"},
	"D1210": {"Commerce", "Alimentaire", "Prestation", "Confort"},
	"D1211": {"Commerce", "Alimentaire", "Prestation", "Confort"},
	"D1212": {"Commerce", "Alimentaire", "Prestation", "Confort"},
	"D1213": {"Commerce", "Alimentaire", "Prestation", "Confort"},
	"D1214": {"Commerce", "Alimentaire", "Prestation", "Confort"},
	"D1301": {"Direction", "Magasin", "Détail"},
	"D1401": {"Force", "Vente"},
	"D1402": {"Force", "Vente"},
	"D1403": {"Force", "Vente"},
	"D1404": {"Force", "Vente"},
	"D1405": {"Force", "Vente"},
	"D1406": {"Force", "Vente"},
	"D1407": {"Force", "Vente"},
	"D1408": {"Force", "Vente"},
	"D1501": {"Grande", "Distribution"},
	"D1502": {"Grande", "Distribution"},
	"D1503": {"Grande", "Distribution"},
	"D1504": {"Grande", "Distribution"},
	"D1505": {"Grande", "Distribution"},
	"D1506": {"Grande", "Distribution"},
	"D1507": {"Grande", "Distribution"},
	"D1508": {"Grande", "Distribution"},
	"D1509": {"Grande", "Distribution"},
	"E1101": {"Édition", "Communication"},
	"E1102": {"Édition", "Communication"},
	"E1103": {"Édition", "Communication"},
	"E1104": {"Édition", "Communication"},
	"E1105": {"Édition", "Communication"},
	"E1106": {"Édition", "Communication"},
	"E1107": {"Édition", "Communication"},
	"E1108": {"Édition", "Communication"},
	"E1201": {"Image", "Son"},
	"E1202": {"Image", "Son"},
	"E1203": {"Image", "Son"},
	"E1204": {"Image", "Son"},
	"E1205": {"Image", "Son"},
	"E1301": {"Industrie", "Graphique"},
	"E1302": {"Industrie", "Graphique"},
	"E1303": {"Industrie", "Graphique"},
	"E1304": {"Industrie", "Graphique"},
	"E1305": {"Industrie", "Graphique"},
	"E1306": {"Industrie", "Graphique"},
	"E1307": {"Industrie", "Graphique"},
	"E1308": {"Industrie", "Graphique"},
	"E1401": {"Publicité"},
	"E1402": {"Publicité"},
	"F1101": {"Conception", "Étude"},
	"F1102": {"Conception", "Étude"},
	"F1103": {"Conception", "Étude"},
	"F1104": {"Conception", "Étude"},
	"F1105": {"Conception", "Étude"},
	"F1106": {"Conception", "Étude"},
	"F1107": {"Conception", "Étude"},
	"F1108": {"Conception", "Étude"},
	"F1201": {"Conduite", "Encadrement", "Chantier", "Travaux"},
	"F1202": {"Conduite", "Encadrement", "Chantier", "Travaux"},
	"F1203": {"Conduite", "Encadrement", "Chantier", "Travaux"},
	"F1204": {"Conduite", "Encadrement", "Chantier", "Travaux"},
	"F1301": {"Engin", "Chantier"},
	"F1302": {"Engin", "Chantier"},
	"F1401": {"Extraction"},
	"F1402": {"Extraction"},
	"F1501": {"Montage", "Structure"},
	"F1502": {"Montage", "Structure"},
	"F1503": {"Montage", "Structure"},
	"F1601": {"Second Œuvre"},
	"F1602": {"Second Œuvre"},
	"F1603": {"Second Œuvre"},
	"F1604": {"Second Œuvre"},
	"F1605": {"Second Œuvre"},
	"F1606": {"Second Œuvre"},
	"F1607": {"Second Œuvre"},
	"F1608": {"Second Œuvre"},
	"F1609": {"Second Œuvre"},
	"F1610": {"Second Œuvre"},
	"F1611": {"Second Œuvre"},
	"F1612": {"Second Œuvre"},
	"F1613": {"Second Œuvre"},
	"F1701": {"Travaux", "Gros"},
	"F1702": {"Travaux", "Gros"},
	"F1703": {"Travaux", "Gros"},
	"F1704": {"Travaux", "Gros"},
	"F1705": {"Travaux", "Gros"},
	"F1706": {"Travaux", "Gros"},
	"G1101": {"Accueil", "Promotion", "Touristique"},
	"G1102": {"Accueil", "Promotion", "Touristique"},
	"G1201": {"Animation", "Activité", "Loisir"},
	"G1202": {"Animation", "Activité", "Loisir"},
	"G1203": {"Animation", "Activité", "Loisir"},
	"G1204": {"Animation", "Activité", "Loisir"},
	"G1205": {"Animation", "Activité", "Loisir"},
	"G1206": {"Animation", "Activité", "Loisir"},
	"G1301": {"Conception", "Vente", "Produit", "Touristique"},
	"G1302": {"Conception", "Vente", "Produit", "Touristique"},
	"G1303": {"Conception", "Vente", "Produit", "Touristique"},
	"G1401": {"Gestion", "Direction"},
	"G1402": {"Gestion", "Direction"},
	"G1403": {"Gestion", "Direction"},
	"G1404": {"Gestion", "Direction"},
	"G1501": {"Hôtellerie"},
	"G1502": {"Hôtellerie"},
	"G1503": {"Hôtellerie"},
	"G1601": {"Production", "Culinaire"},
	"G1602": {"Production", "Culinaire"},
	"G1603": {"Production", "Culinaire"},
	"G1604": {"Production", "Culinaire"},
	"G1605": {"Production", "Culinaire"},
	"G1701": {"Accueil", "Hôtellerie"},
	"G1702": {"Accueil", "Hôtellerie"},
	"G1703": {"Accueil", "Hôtellerie"},
	"G1801": {"Service"},
	"G1802": {"Service"},
	"G1803": {"Service"},
	"G1804": {"Service"},
	"H1101": {"Affaire", "Support", "Technique", "Client"},
	"H1102": {"Affaire", "Support", "Technique", "Client"},
	"H1201": {"Conception", "Recherche", "Étude", "Développement"},
	"H1202": {"Conception", "Recherche", "Étude", "Développement"},
	"H1203": {"Conception", "Recherche", "Étude", "Développement"},
	"H1204": {"Conception", "Recherche", "Étude", "Développement"},
	"H1205": {"Conception", "Recherche", "Étude", "Développement"},
	"H1206": {"Conception", "Recherche", "Étude", "Développement"},
	"H1207": {"Conception", "Recherche", "Étude", "Développement"},
	"H1208": {"Conception", "Recherche", "Étude", "Développement"},
	"H1209": {"Conception", "Recherche", "Étude", "Développement"},
	"H1210": {"Conception", "Recherche", "Étude", "Développement"},
	"H1301": {"Hygiène", "Sécurité", "Environnement", "HSE", "Industriel"},
	"H1302": {"Hygiène", "Sécurité", "Environnement", "HSE", "Industriel"},
	"H1303": {"Hygiène", "Sécurité", "Environnement", "HSE", "Industriel"},
	"H1401": {"Méthode", "Gestion", "Industrielle"},
	"H1402": {"Méthode", "Gestion", "Industrielle"},
	"H1403": {"Méthode", "Gestion", "Industrielle"},
	"H1404": {"Méthode", "Gestion", "Industrielle"},
	"H1501": {"Qualité", "Analyse", "Industrielle"},
	"H1502": {"Qualité", "Analyse", "Industrielle"},
	"H1503": {"Qualité", "Analyse", "Industrielle"},
	"H1504": {"Qualité", "Analyse", "Industrielle"},
	"H1505": {"Qualité", "Analyse", "Industrielle"},
	"H1506": {"Qualité", "Analyse", "Industrielle"},
	"H2101": {"Alimentaire"},
	"H2102": {"Alimentaire"},
	"H2201": {"Bois"},
	"H2202": {"Bois"},
	"H2203": {"Bois"},
	"H2204": {"Bois"},
	"H2205": {"Bois"},
	"H2206": {"Bois"},
	"H2207": {"Bois"},
	"H2208": {"Bois"},
	"H2209": {"Bois"},
	"H2301": {"Chimie", "Pharmacie"},
	"H2401": {"Cuir", "Textile"},
	"H2402": {"Cuir", "Textile"},
	"H2403": {"Cuir", "Textile"},
	"H2404": {"Cuir", "Textile"},
	"H2405": {"Cuir", "Textile"},
	"H2406": {"Cuir", "Textile"},
	"H2407": {"Cuir", "Textile"},
	"H2408": {"Cuir", "Textile"},
	"H2409": {"Cuir", "Textile"},
	"H2410": {"Cuir", "Textile"},
	"H2411": {"Cuir", "Textile"},
	"H2412": {"Cuir", "Textile"},
	"H2413": {"Cuir", "Textile"},
	"H2414": {"Cuir", "Textile"},
	"H2415": {"Cuir", "Textile"},
	"H2501": {"Direction", "Encadrement", "Pilotage", "Fabrication", "Production", "Industrielle"},
	"H2502": {"Direction", "Encadrement", "Pilotage", "Fabrication", "Production", "Industrielle"},
	"H2503": {"Direction", "Encadrement", "Pilotage", "Fabrication", "Production", "Industrielle"},
	"H2504": {"Direction", "Encadrement", "Pilotage", "Fabrication", "Production", "Industrielle"},
	"H2505": {"Direction", "Encadrement", "Pilotage", "Fabrication", "Production", "Industrielle"},
	"H2601": {"Électronique", "Électricité"},
	"H2602": {"Électronique", "Électricité"},
	"H2603": {"Électronique", "Électricité"},
	"H2604": {"Électronique", "Électricité"},
	"H2605": {"Électronique", "Électricité"},
	"H2701": {"Énergie"},
	"H2801": {"Matériaux", "Construction", "Céramique", "Verre"},
	"H2802": {"Matériaux", "Construction", "Céramique", "Verre"},
	"H2803": {"Matériaux", "Construction", "Céramique", "Verre"},
	"H2804": {"Matériaux", "Construction", "Céramique", "Verre"},
	"H2805": {"Matériaux", "Construction", "Céramique", "Verre"},
	"H2901": {"Mécanique", "Travail", "Métaux", "Outillage"},
	"H2902": {"Mécanique", "Travail", "Métaux", "Outillage"},
	"H2903": {"Mécanique", "Travail", "Métaux", "Outillage"},
	"H2904": {"Mécanique", "Travail", "Métaux", "Outillage"},
	"H2905": {"Mécanique", "Travail", "Métaux", "Outillage"},
	"H2906": {"Mécanique", "Travail", "Métaux", "Outillage"},
	"H2907": {"Mécanique", "Travail", "Métaux", "Outillage"},
	"H2908": {"Mécanique", "Travail", "Métaux", "Outillage"},
	"H2909": {"Mécanique", "Travail", "Métaux", "Outillage"},
	"H2910": {"Mécanique", "Travail", "Métaux", "Outillage"},
	"H2911": {"Mécanique", "Travail", "Métaux", "Outillage"},
	"H2912": {"Mécanique", "Travail", "Métaux", "Outillage"},
	"H2913": {"Mécanique", "Travail", "Métaux", "Outillage"},
	"H2914": {"Mécanique", "Travail", "Métaux", "Outillage"},
	"H3101": {"Papier", "Carton"},
	"H3102": {"Papier", "Carton"},
	"H3201": {"Plastique", "Caoutchouc"},
	"H3202": {"Plastique", "Caoutchouc"},
	"H3203": {"Plastique", "Caoutchouc"},
	"H3301": {"Préparation", "Conditionnement"},
	"H3302": {"Préparation", "Conditionnement"},
	"H3303": {"Préparation", "Conditionnement"},
	"H3401": {"Traitement", "Thermique", "Surface"},
	"H3402": {"Traitement", "Thermique", "Surface"},
	"H3403": {"Traitement", "Thermique", "Surface"},
	"H3404": {"Traitement", "Thermique", "Surface"},
	"I1101": {"Encadrement"},
	"I1102": {"Encadrement"},
	"I1103": {"Encadrement"},
	"I1201": {"Entretien", "Technique"},
	"I1202": {"Entretien", "Technique"},
	"I1203": {"Entretien", "Technique"},
	"I1301": {"Équipement", "Production", "Collectif"},
	"I1302": {"Équipement", "Production", "Collectif"},
	"I1303": {"Équipement", "Production", "Collectif"},
	"I1304": {"Équipement", "Production", "Collectif"},
	"I1305": {"Équipement", "Production", "Collectif"},
	"I1306": {"Équipement", "Production", "Collectif"},
	"I1307": {"Équipement", "Production", "Collectif"},
	"I1308": {"Équipement", "Production", "Collectif"},
	"I1309": {"Équipement", "Production", "Collectif"},
	"I1310": {"Équipement", "Production", "Collectif"},
	"I1401": {"Équipement", "Domestique", "Informatique"},
	"I1402": {"Équipement", "Domestique", "Informatique"},
	"I1501": {"Travaux", "Accès", "Difficile"},
	"I1502": {"Travaux", "Accès", "Difficile"},
	"I1503": {"Travaux", "Accès", "Difficile"},
	"I1601": {"Véhicule", "Engin", "Aéronef"},
	"I1602": {"Véhicule", "Engin", "Aéronef"},
	"I1603": {"Véhicule", "Engin", "Aéronef"},
	"I1604": {"Véhicule", "Engin", "Aéronef"},
	"I1605": {"Véhicule", "Engin", "Aéronef"},
	"I1606": {"Véhicule", "Engin", "Aéronef"},
	"I1607": {"Véhicule", "Engin", "Aéronef"},
	"J1101": {"Praticien", "Médicaux"},
	"J1102": {"Praticien", "Médicaux"},
	"J1103": {"Praticien", "Médicaux"},
	"J1104": {"Praticien", "Médicaux"},
	"J1201": {"Praticien", "Médicotechnique"},
	"J1202": {"Praticien", "Médicotechnique"},
	"J1301": {"Médicotechnique"},
	"J1302": {"Médicotechnique"},
	"J1303": {"Médicotechnique"},
	"J1304": {"Médicotechnique"},
	"J1305": {"Médicotechnique"},
	"J1306": {"Médicotechnique"},
	"J1307": {"Médicotechnique"},
	"J1401": {"Rééducation", "Appareillage"},
	"J1402": {"Rééducation", "Appareillage"},
	"J1403": {"Rééducation", "Appareillage"},
	"J1404": {"Rééducation", "Appareillage"},
	"J1405": {"Rééducation", "Appareillage"},
	"J1406": {"Rééducation", "Appareillage"},
	"J1407": {"Rééducation", "Appareillage"},
	"J1408": {"Rééducation", "Appareillage"},
	"J1409": {"Rééducation", "Appareillage"},
	"J1410": {"Rééducation", "Appareillage"},
	"J1411": {"Rééducation", "Appareillage"},
	"J1412": {"Rééducation", "Appareillage"},
	"J1501": {"Soin", "Paramédicaux"},
	"J1502": {"Soin", "Paramédicaux"},
	"J1503": {"Soin", "Paramédicaux"},
	"J1504": {"Soin", "Paramédicaux"},
	"J1505": {"Soin", "Paramédicaux"},
	"J1506": {"Soin", "Paramédicaux"},
	"J1507": {"Soin", "Paramédicaux"},
	"K1101": {"Accompagnement", "Personne"},
	"K1102": {"Accompagnement", "Personne"},
	"K1103": {"Accompagnement", "Personne"},
	"K1104": {"Accompagnement", "Personne"},
	"K1201": {"Action", "Sociale", "Socioéducative", "Socioculturelle"},
	"K1202": {"Action", "Sociale", "Socioéducative", "Socioculturelle"},
	"K1203": {"Action", "Sociale", "Socioéducative", "Socioculturelle"},
	"K1204": {"Action", "Sociale", "Socioéducative", "Socioculturelle"},
	"K1205": {"Action", "Sociale", "Socioéducative", "Socioculturelle"},
	"K1206": {"Action", "Sociale", "Socioéducative", "Socioculturelle"},
	"K1207": {"Action", "Sociale", "Socioéducative", "Socioculturelle"},
	"K1301": {"Aide", "Quotidienne"},
	"K1302": {"Aide", "Quotidienne"},
	"K1303": {"Aide", "Quotidienne"},
	"K1304": {"Aide", "Quotidienne"},
	"K1305": {"Aide", "Quotidienne"},
	"K1401": {"Conception", "Politique", "Publique"},
	"K1402": {"Conception", "Politique", "Publique"},
	"K1403": {"Conception", "Politique", "Publique"},
	"K1404": {"Conception", "Politique", "Publique"},
	"K1405": {"Conception", "Politique", "Publique"},
	"K1501": {"Contrôle", "Public"},
	"K1502": {"Contrôle", "Public"},
	"K1503": {"Contrôle", "Public"},
	"K1504": {"Contrôle", "Public"},
	"K1505": {"Contrôle", "Public"},
	"K1601": {"Culture", "Gestion", "Documentaire"},
	"K1602": {"Culture", "Gestion", "Documentaire"},
	"K1701": {"Défense", "Sécurité", "Publique", "Secours"},
	"K1702": {"Défense", "Sécurité", "Publique", "Secours"},
	"K1703": {"Défense", "Sécurité", "Publique", "Secours"},
	"K1704": {"Défense", "Sécurité", "Publique", "Secours"},
	"K1705": {"Défense", "Sécurité", "Publique", "Secours"},
	"K1706": {"Défense", "Sécurité", "Publique", "Secours"},
	"K1707": {"Défense", "Sécurité", "Publique", "Secours"},
	"K1801": {"Développement", "Territorial", "Emploi"},
	"K1802": {"Développement", "Territorial", "Emploi"},
	"K1901": {"Droit"},
	"K1902": {"Droit"},
	"K1903": {"Droit"},
	"K1904": {"Droit"},
	"K2101": {"Formation", "Initiale", "Continue"},
	"K2102": {"Formation", "Initiale", "Continue"},
	"K2103": {"Formation", "Initiale", "Continue"},
	"K2104": {"Formation", "Initiale", "Continue"},
	"K2105": {"Formation", "Initiale", "Continue"},
	"K2106": {"Formation", "Initiale", "Continue"},
	"K2107": {"Formation", "Initiale", "Continue"},
	"K2108": {"Formation", "Initiale", "Continue"},
	"K2109": {"Formation", "Initiale", "Continue"},
	"K2110": {"Formation", "Initiale", "Continue"},
	"K2111": {"Formation", "Initiale", "Continue"},
	"K2112": {"Formation", "Initiale", "Continue"},
	"K2201": {"Nettoyage", "Propreté", "Industriel"},
	"K2202": {"Nettoyage", "Propreté", "Industriel"},
	"K2203": {"Nettoyage", "Propreté", "Industriel"},
	"K2204": {"Nettoyage", "Propreté", "Industriel"},
	"K2301": {"Propreté", "Environnement", "Urbain"},
	"K2302": {"Propreté", "Environnement", "Urbain"},
	"K2303": {"Propreté", "Environnement", "Urbain"},
	"K2304": {"Propreté", "Environnement", "Urbain"},
	"K2305": {"Propreté", "Environnement", "Urbain"},
	"K2306": {"Propreté", "Environnement", "Urbain"},
	"K2401": {"Recherche"},
	"K2402": {"Recherche"},
	"K2501": {"Sécurité", "Privée"},
	"K2502": {"Sécurité", "Privée"},
	"K2503": {"Sécurité", "Privée"},
	"K2601": {"Service", "Funéraire"},
	"K2602": {"Service", "Funéraire"},
	"K2603": {"Service", "Funéraire"},
	"L1101": {"Animation", "Spectacle"},
	"L1102": {"Animation", "Spectacle"},
	"L1103": {"Animation", "Spectacle"},
	"L1201": {"Artiste", "Interprète", "Spectacle"},
	"L1202": {"Artiste", "Interprète", "Spectacle"},
	"L1203": {"Artiste", "Interprète", "Spectacle"},
	"L1204": {"Artiste", "Interprète", "Spectacle"},
	"L1301": {"Conception", "Production", "Spectacle"},
	"L1302": {"Conception", "Production", "Spectacle"},
	"L1303": {"Conception", "Production", "Spectacle"},
	"L1304": {"Conception", "Production", "Spectacle"},
	"L1401": {"Sport"},
	"L1501": {"Technicien", "Spectacle"},
	"L1502": {"Technicien", "Spectacle"},
	"L1503": {"Technicien", "Spectacle"},
	"L1504": {"Technicien", "Spectacle"},
	"L1505": {"Technicien", "Spectacle"},
	"L1506": {"Technicien", "Spectacle"},
	"L1507": {"Technicien", "Spectacle"},
	"L1508": {"Technicien", "Spectacle"},
	"L1509": {"Technicien", "Spectacle"},
	"M1101": {"Achat"},
	"M1102": {"Achat"},
	"M1201": {"Comptabilité", "Gestion"},
	"M1202": {"Comptabilité", "Gestion"},
	"M1203": {"Comptabilité", "Gestion"},
	"M1204": {"Comptabilité", "Gestion"},
	"M1205": {"Comptabilité", "Gestion"},
	"M1206": {"Comptabilité", "Gestion"},
	"M1207": {"Comptabilité", "Gestion"},
	"M1301": {"Direction", "Entreprise"},
	"M1302": {"Direction", "Entreprise"},
	"M1401": {"Organisation", "Étude"},
	"M1402": {"Organisation", "Étude"},
	"M1403": {"Organisation", "Étude"},
	"M1404": {"Organisation", "Étude"},
	"M1501": {"Ressource", "Humaine"},
	"M1502": {"Ressource", "Humaine"},
	"M1503": {"Ressource", "Humaine"},
	"M1601": {"Secrétariat", "Assistance"},
	"M1602": {"Secrétariat", "Assistance"},
	"M1603": {"Secrétariat", "Assistance"},
	"M1604": {"Secrétariat", "Assistance"},
	"M1605": {"Secrétariat", "Assistance"},
	"M1606": {"Secrétariat", "Assistance"},
	"M1607": {"Secrétariat", "Assistance"},
	"M1608": {"Secrétariat", "Assistance"},
	"M1609": {"Secrétariat", "Assistance"},
	"M1701": {"Stratégie", "Commerce", "Marketing", "Supervision", "Vente"},
	"M1702": {"Stratégie", "Commerce", "Marketing", "Supervision", "Vente"},
	"M1703": {"Stratégie", "Commerce", "Marketing", "Supervision", "Vente"},
	"M1704": {"Stratégie", "Commerce", "Marketing", "Supervision", "Vente"},
	"M1705": {"Stratégie", "Commerce", "Marketing", "Supervision", "Vente"},
	"M1706": {"Stratégie", "Commerce", "Marketing", "Supervision", "Vente"},
	"M1707": {"Stratégie", "Commerce", "Marketing", "Supervision", "Vente"},
	"M1801": {"Système", "Information", "Télécommunication"},
	"M1802": {"Système", "Information", "Télécommunication"},
	"M1803": {"Système", "Information", "Télécommunication"},
	"M1804": {"Système", "Information", "Télécommunication"},
	"M1805": {"Système", "Information", "Télécommunication"},
	"M1806": {"Système", "Information", "Télécommunication"},
	"M1807": {"Système", "Information", "Télécommunication"},
	"M1808": {"Système", "Information", "Télécommunication"},
	"M1809": {"Système", "Information", "Télécommunication"},
	"M1810": {"Système", "Information", "Télécommunication"},
	"N1101": {"Magasinage", "Manutention", "Charge", "Déménagement"},
	"N1102": {"Magasinage", "Manutention", "Charge", "Déménagement"},
	"N1103": {"Magasinage", "Manutention", "Charge", "Déménagement"},
	"N1104": {"Magasinage", "Manutention", "Charge", "Déménagement"},
	"N1105": {"Magasinage", "Manutention", "Charge", "Déménagement"},
	"N1201": {"Organisation", "Circulation", "Marchandise"},
	"N1202": {"Organisation", "Circulation", "Marchandise"},
	"N1301": {"Encadrement"},
	"N1302": {"Encadrement"},
	"N1303": {"Encadrement"},
	"N2101": {"Navigant", "Transport", "Aérien"},
	"N2102": {"Navigant", "Transport", "Aérien"},
	"N2201": {"Transport", "Aérien"},
	"N2202": {"Transport", "Aérien"},
	"N2203": {"Transport", "Aérien"},
	"N2204": {"Transport", "Aérien"},
	"N2205": {"Transport", "Aérien"},
	"N3101": {"Navigant", "Transport", "Maritime", "Fluvial"},
	"N3102": {"Navigant", "Transport", "Maritime", "Fluvial"},
	"N3103": {"Navigant", "Transport", "Maritime", "Fluvial"},
	"N3201": {"Transport", "Maritime", "Fluvial"},
	"N3202": {"Transport", "Maritime", "Fluvial"},
	"N3203": {"Transport", "Maritime", "Fluvial"},
	"N4101": {"Conduite", "Transport", "Routier"},
	"N4102": {"Conduite", "Transport", "Routier"},
	"N4103": {"Conduite", "Transport", "Routier"},
	"N4104": {"Conduite", "Transport", "Routier"},
	"N4105": {"Conduite", "Transport", "Routier"},
	"N4201": {"Encadrement", "Transport", "Routier"},
	"N4202": {"Encadrement", "Transport", "Routier"},
	"N4203": {"Encadrement", "Transport", "Routier"},
	"N4204": {"Encadrement", "Transport", "Routier"},
	"N4301": {"Navigant", "Transport", "Terrestre"},
	"N4302": {"Navigant", "Transport", "Terrestre"},
	"N4401": {"Transport", "Ferroviaire", "Réseau"},
	"N4402": {"Transport", "Ferroviaire", "Réseau"},
	"N4403": {"Transport", "Ferroviaire", "Réseau"},
}

func GetRomeCodes() []string {
	codes := make([]string, 0, len(romes))

	for code := range romes {
		codes = append(codes, code)
	}

	return codes
}

func GetRomeTags(code string) []string {
	tags := []string{}

	values, ok := romes[code]
	if ok {
		for _, value := range values {
			if !isIn(value, tags) {
				tags = append(tags, value)
			}
		}
	}

	return tags
}

func GetAllRomeTags() []string {
	tags := []string{}

	for _, values := range romes {
		for _, value := range values {
			if !isIn(value, tags) {
				tags = append(tags, value)
			}
		}
	}

	return tags
}

func isIn(str string, array []string) bool {
	for _, f := range array {
		if f == str {
			return true
		}
	}

	return false
}
