CREATE TABLE IF NOT EXISTS `category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `public_id` VARCHAR(20) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQ_64C19C1B5B48B91` (`public_id` ASC) VISIBLE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `company` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `public_id` VARCHAR(20) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `siret` VARCHAR(14) NULL DEFAULT NULL,
  `contact_email` VARCHAR(120) NULL DEFAULT NULL,
  `phone_number` VARCHAR(20) NULL DEFAULT NULL,
  `website_url` VARCHAR(255) NULL DEFAULT NULL,
  `logo` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `verified` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQ_4FBF094FB5B48B91` (`public_id` ASC) VISIBLE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `offer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) NULL DEFAULT NULL,
  `public_id` VARCHAR(20) NOT NULL,
  `title` VARCHAR(120) NOT NULL,
  `place` JSON NOT NULL,
  `job` JSON NOT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `tag` JSON NULL DEFAULT NULL,
  `status` VARCHAR(40) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `end_date` DATE NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `premium` TINYINT(1) NOT NULL,
  `external_id` VARCHAR(255) NULL DEFAULT NULL,
  `service_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQ_29D6873EB5B48B91` (`public_id` ASC) VISIBLE,
  INDEX `IDX_29D6873E979B1AD6` (`company_id` ASC) VISIBLE,
  CONSTRAINT `FK_29D6873E979B1AD6` FOREIGN KEY (`company_id`) REFERENCES `jaltup`.`company` (`id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `offer_category` (
  `offer_id` INT(11) NOT NULL,
  `category_id` INT(11) NOT NULL,
  PRIMARY KEY (`offer_id`, `category_id`),
  INDEX `IDX_7F31A9A353C674EE` (`offer_id` ASC) VISIBLE,
  INDEX `IDX_7F31A9A312469DE2` (`category_id` ASC) VISIBLE,
  CONSTRAINT `FK_7F31A9A312469DE2` FOREIGN KEY (`category_id`) REFERENCES `jaltup`.`category` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_7F31A9A353C674EE` FOREIGN KEY (`offer_id`) REFERENCES `jaltup`.`offer` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `refresh_tokens` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `refresh_token` VARCHAR(128) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `valid` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQ_9BACE7E1C74F2195` (`refresh_token` ASC) VISIBLE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(180) NOT NULL,
  `roles` JSON NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `public_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQ_IDENTIFIER_EMAIL` (`email` ASC) VISIBLE,
  UNIQUE INDEX `UNIQ_8D93D649B5B48B91` (`public_id` ASC) VISIBLE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;